services:
  security-scanner:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - API_KEYS=${API_KEYS:-your-secure-production-key-2025}
      - PORT=3000
      # GitLab configuration
      - GITLAB_TOKEN=${GITLAB_TOKEN:-}
      - GITLAB_ACCESS_TOKEN=${GITLAB_ACCESS_TOKEN:-}
      # GitHub configuration (existing)
      - GITHUB_TOKEN=${GITHUB_TOKEN:-}
    volumes:
      # Optional: Mount logs directory if you want to persist logs
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - scanner-network

networks:
  scanner-network:
    driver: bridge 