services:
  security-scanner:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - API_KEYS=${API_KEYS:-your-secure-production-key-2025}
      - PORT=3000
      # Rate Limiting (Throttler) Configuration
      - THROTTLE_TTL=${THROTTLE_TTL:-60}
      - THROTTLE_LIMIT=${THROTTLE_LIMIT:-10}
      - SCAN_THROTTLE_TTL=${SCAN_THROTTLE_TTL:-300}
      - SCAN_THROTTLE_LIMIT=${SCAN_THROTTLE_LIMIT:-5}
      - METADATA_THROTTLE_TTL=${METADATA_THROTTLE_TTL:-60}
      - METADATA_THROTTLE_LIMIT=${METADATA_THROTTLE_LIMIT:-20}
      # GitLab configuration
      - GITLAB_TOKEN=${GITLAB_TOKEN:-}
      - GITLAB_ACCESS_TOKEN=${GITLAB_ACCESS_TOKEN:-}
      # GitHub configuration (existing)
      - GITHUB_TOKEN=${GITHUB_TOKEN:-}
      # Bitbucket configuration
      - BITBUCKET_TOKEN=${BITBUCKET_TOKEN:-}
      - BITBUCKET_APP_PASSWORD=${BITBUCKET_APP_PASSWORD:-}
    volumes:
      # Optional: Mount logs directory if you want to persist logs
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - scanner-network

networks:
  scanner-network:
    driver: bridge 